apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample_app_be
  namespace: argocd
  labels:
    app: sample_app_be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample_app_be
  template:
    metadata:
      labels:
        app: sample_app_be
    spec:
      containers:
      - name: sample_app_be
        image: docker.io/ackresponse/sample_app_be:latest
        ports:
        - containerPort: 8080
