apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-be
  namespace: argocd
  labels:
    app: sample-app-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-be
  template:
    metadata:
      labels:
        app: sample-app-be
    spec:
      containers:
      - name: sample-app-be
        image: docker.io/ackresponse/sample-app-be:1.0
        ports:
        - containerPort: 8080
        