apiVersion: v1
kind: Service
metadata:
  name: sample-app-be-service
  namespace: argocd
  labels:
    app: sample-app-be
spec:
  type: ClusterIP
  selector:
    app: sample-app-be
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080