apiVersion: v1
kind: Service
metadata:
  name: sample_app_be_service
  namespace: argocd
  labels:
    app: sample_app_be
spec:
  type: LoadBalancer
  selector:
    app: sample_app_be
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
